Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 150

AllCops:
  Exclude:
  - '.kitchen/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters: { "default" => "()", "%i" => "[]", "%I" => "[]", "%r" => "{}", "%w" => "()", "%W" => "[]" }
