language: ruby
os: linux
dist: focal

matrix:
  include:
  - rvm: 2.7.1
  - rvm: 2.7.1
    services: docker
    sudo: required
    env:
      - KITCHEN_YAML=kitchen.travis.yml
      - CHEF_LICENSE=accept-no-persist
    before_script:
      # - sudo curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P 'chef-workstation'
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      # - eval "$(chef shell-init bash)"
      # - chef --version
    script:
      - time bundle exec kitchen verify
    after_failure:
      - cat .kitchen/logs/kitchen.log

branches:
  only:
  - master
