language: ruby

matrix:
  include:
  - rvm: 2.5.3
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - chef-current-xenial
        packages:
          - chef-workstation
    services: docker
    sudo: required
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - eval "$(chef shell-init bash)"
      - chef --version
    script:
      - CHEF_LICENSE=accept-no-persist
      - time bundle exec kitchen verify
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=20.04
      - KITCHEN_YAML=kitchen.travis.yml

branches:
  only:
  - master
