os: linux

dist: focal

before_install:
  - sudo apt-get -y install libxml2-dev

addons:
  apt:
    update: true

sudo: required

env:
  global:
    - UBUNTU=20.04
    - KITCHEN_YAML=kitchen.travis.yml
    - CHEF_LICENSE=accept-no-persist

before_script:
  - sudo curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P 'chef-workstation'
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

matrix:
  include:
  - script:
      - rspec spec
  - services: docker
    script:
      - chef gem build ./kitchen-nodes.gemspec
      - chef gem install ./kitchen-nodes*.gem kitchen-docker
      - time kitchen verify
    after_failure:
      - cat .kitchen/logs/kitchen.log

branches:
  only:
  - master
