language: ruby

matrix:
  include:
  - rvm: ruby-head
  - rvm: ruby-head
    services: docker
    sudo: required
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
    script:
      - time bundle exec kitchen verify
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=20.04
      - KITCHEN_YAML=kitchen.travis.yml

branches:
  only:
  - master
