---
driver:
  name: docker
  username: vagrant
  provision_command:
    - sudo usermod -p $(echo vagrant | openssl passwd -1 -stdin) vagrant
    - sudo locale-gen en_US.UTF-8
    - sudo echo 'LANG=en_US.UTF-8' >> /etc/environment

provisioner:
  name: nodes
  roles_path: test/fixtures/roles
  product_name: chef
  product_version: latest
  chef_license: accept-no-persist

platforms:
- name: ubuntu-20.04
  driver_config:
    image: dokken/ubuntu-20.04
    platform: debian

suites:
- name: node1
  run_list:
  - role[test_json_role]
  - role[test_ruby_role]
  - recipe[node-tests::node1]
  attributes:
    consul:
      config:
        bootstrap_expect: 2
        server: true

- name: node2
  run_list:
  - recipe[node-tests::node2]
  attributes:
    consul:
      config:
        bootstrap_expect: 2
        server: true
